objects/Account.object
<CustomObject>
    <fields>
        <fullName>Audits_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if the current or next audit of the parent cert includes this cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>Audits Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BR_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>BR Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>BR_Audit__c</fullName>
        <description>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://wiki.mozilla.org/CA:SalesforceCommunity#Documents.</description>
        <inlineHelpText>If able to issue SSL/TLS certs, then URL to Baseline Requirements audit statement. Documents may be attached to Bugzilla Bugs as described here https://wiki.mozilla.org/CA:SalesforceCommunity#Documents.</inlineHelpText>
        <label>BR Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CA_Owner_ID__c</fullName>
        <description>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</description>
        <inlineHelpText>This field stores the CA Owner ID - top level in hierarchy. It is updated by workflow - field update.</inlineHelpText>
        <label>CA Owner ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CA_Owner__c</fullName>
        <description>This field shows the CA Owner - top level in hierarchy.</description>
        <inlineHelpText>This field shows the CA Owner - top level in hierarchy.</inlineHelpText>
        <label>CA Owner</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CP_CPS_Same_as_Parent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click this box if this cert does not have separate policy documentation from the parent cert. If you click this box do NOT enter data into the other fields in this section.</description>
        <inlineHelpText>Click this box if this cert does not have separate policy documentation from the parent cert. If you click this box do NOT enter data into the other fields in this section.</inlineHelpText>
        <label>CP/CPS Same as Parent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Certificate_Policy_CP__c</fullName>
        <description>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://wiki.mozilla.org/CA:SalesforceCommunity#Documents.</description>
        <inlineHelpText>URL to Certificate Policy documentation specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://wiki.mozilla.org/CA:SalesforceCommunity#Documents.</inlineHelpText>
        <label>Certificate Policy (CP)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Certification_Practice_Statement_CPS__c</fullName>
        <description>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://wiki.mozilla.org/CA:SalesforceCommunity#Documents.</description>
        <inlineHelpText>URL to CPS specific to this cert. Documents may be attached to Bugzilla Bugs as described here https://wiki.mozilla.org/CA:SalesforceCommunity#Documents.</inlineHelpText>
        <label>Certification Practice Statement (CPS)</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit_Period_End_Date__c</fullName>
        <description>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</description>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Code Signing Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Code_Signing_Audit__c</fullName>
        <label>Code Signing Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>EV SSL Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Audit__c</fullName>
        <description>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://wiki.mozilla.org/CA:SalesforceCommunity#Documents.</description>
        <inlineHelpText>If able to issue EV certs, then URL to EV audit statement. Documents may be attached to Bugzilla Bugs as described here https://wiki.mozilla.org/CA:SalesforceCommunity#Documents.</inlineHelpText>
        <label>EV SSL Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>EV Code Signing Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EV_Code_Signing_Audit__c</fullName>
        <label>EV Code Signing Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Microsoft_Status__c</fullName>
        <label>Microsoft Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Included</fullName>
                    <default>true</default>
                    <label>Not Included</label>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>NotBefore</fullName>
                </value>
                <value>
                    <fullName>Disabled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Problem_Reporting_Mechanism__c</fullName>
        <inlineHelpText>Instructions for reporting suspected Private Key Compromise, Certificate misuse, or other types of fraud, compromise, misuse, inappropriate conduct, or any other matter related to Certificates.</inlineHelpText>
        <label>Problem Reporting Mechanism</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recognized_CAA_Domains__c</fullName>
        <inlineHelpText>Certification Authority Authorization (CAA) domain names recognized in a CAA record&apos;s issue and issue wild property tags. Comma-separated list.</inlineHelpText>
        <label>Recognized CAA Domains</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <formula>$RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revocation_Status__c</fullName>
        <label>Revocation Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Revoked</fullName>
                    <default>true</default>
                    <label>Not Revoked</label>
                </value>
                <value>
                    <fullName>Revoked</fullName>
                </value>
                <value>
                    <fullName>Parent Cert Revoked</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Root_Status__c</fullName>
        <formula>TEXT( Root_Cert_Id__r.Status__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This formula field derives root status from &apos;Root Cert Id&apos; field. &apos;Root Cert Id&apos; is populated for all intermediate certs by PublicAllIntermediateCerts batch program.</inlineHelpText>
        <label>Root Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Audit_Period_End_Date__c</fullName>
        <inlineHelpText>End date of the period of time of CA operations examined by the auditor. Audit Periods must not exceed one year in duration and must be contiguous.</inlineHelpText>
        <label>Standard Audit Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Standard_Audit__c</fullName>
        <description>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://wiki.mozilla.org/CA:SalesforceCommunity#Documents.</description>
        <inlineHelpText>URL to public attestation of conformance to the stated certificate verification requirements by a competent independent party. Documents may be attached to Bugzilla Bugs as described here https://wiki.mozilla.org/CA:SalesforceCommunity#Documents.</inlineHelpText>
        <label>Standard Audit</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Mozilla Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Included</fullName>
                </value>
                <value>
                    <fullName>Change Requested</fullName>
                </value>
                <value>
                    <fullName>Included</fullName>
                </value>
                <value>
                    <fullName>Provided by CA</fullName>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Technically_Constrained__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Technically Constrained</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Valid_To_GMT__c</fullName>
        <inlineHelpText>The date until which the root CA certificate is valid.</inlineHelpText>
        <label>Valid To (GMT)</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>A CA may have more than one person filling the role of Primary Point of Contact (POC), and may use a contractor as one of the POCs.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary POC</fullName>
                </value>
                <value>
                    <fullName>POC</fullName>
                </value>
                <value>
                    <fullName>Auditor</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CAHomePageController.cls
/*******************************************************************************************************
 Name: CAHomePageController

 Dependencies: CAHomePageController controller class, CAHomePage vf page, 
 CAHomePageControllerTest test class

 Description: This is a controller class for CA's Task List (added to home page). It generates
 various reports and a summary wih record count for the CA Owner to which the logged in user is 
 associated. Detail report is only displayed when the record count is greater than 1.
 
 Root Certs with Outdated Audit Statements
 Intermediate Certs with Outdated Audit Statements
 Intermediate Certs with no audit information provided
 Intermediate Certs with no CP/CPS information provided
 Contacts who may be obsolete
 
 Instructions: Add the VF page to CA's home page
 *******************************************************************************************************
 Revision History:
 
     5/31/2019 - Created new class
 ******************************************************************************************************/
 
public without sharing class CAHomePageController {
    
    public List<User> lstUsersNotUsed {get; set;}
    public List<Account> lstOutDatedRootCerts {get; set;}
    public List<Account> lstOutDatedIntermediateCerts {get; set;}
    public List<Account> lstIntermediateCertsNoAudits {get; set;}
    public List<Account> lstIntermediateCertsNoCPCPS {get; set;}
    public string strMissingCAOwnerInfo {get; set;}
    public string strCAOwnerName {get; set;}
    public CAHomePageController(){
        strMissingCAOwnerInfo = '';
        Id userId = UserInfo.getUserId();
        List<User> lstLoggedUser = new List<User>([select Id,Name,AccountId, Account.Name,ContactId from User Where Id =: userId]);
        if(lstLoggedUser.size() > 0 && lstLoggedUser[0].AccountId != null){
            strCAOwnerName = lstLoggedUser[0].Account.Name;
            //check for missing CA Information.
            /*List<Account> lstCAOwnerMF = new List<Account>([select Id,Name,Recognized_CAA_Domains__c,Problem_Reporting_Mechanism__c,
                                BillingStreet, BillingCity, BillingState, BillingCountry, BillingPostalCode,Status__c,Microsoft_Status__c
                                from Account Where RecordType.Name = 'CA Owner' and
                                Id =: lstLoggedUser[0].AccountId]);
            for(Account objAcc: lstCAOwnerMF){
                if(string.isblank(objAcc.BillingStreet)){
                    strMissingCAOwnerInfo += 'Street not provided.<br/>';
                } 
                if(string.isblank(objAcc.BillingCity)){
                    strMissingCAOwnerInfo += 'City not provided.<br/>';
                }
                if(string.isblank(objAcc.BillingState)){
                    strMissingCAOwnerInfo += 'State not provided.<br/>';
                }
                if(string.isblank(objAcc.BillingCountry)){ 
                    strMissingCAOwnerInfo += 'Country not provided.<br/>';
                }
                if(string.isblank(objAcc.BillingPostalCode)){
                    strMissingCAOwnerInfo += 'Postal code not provided.<br/>';
                } 
                if(string.isblank(objAcc.Recognized_CAA_Domains__c)){
                    strMissingCAOwnerInfo += 'Recognized CAA Domains not provided.<br/>';
                }
                if(string.isblank(objAcc.Problem_Reporting_Mechanism__c)){
                    strMissingCAOwnerInfo += 'Problem Reporting Mechanism not provided.<br/>';
                }
            }*/
            
            //checking for outdates root certs.
            lstOutDatedRootCerts = new List<Account>();
            lstOutDatedRootCerts = [SELECT Name, CA_Owner__c, Standard_Audit_Period_End_Date__c,
                            BR_Audit_Period_End_Date__c, Code_Signing_Audit_Period_End_Date__c, 
                            EV_Code_Signing_Audit_Period_End_Date__c, EV_Audit_Period_End_Date__c
                            FROM Account 
                            WHERE Name != '<Fill in Cert Name>'
                            AND Record_Type_Name__c = 'Root Certificate'                           
                            AND (Standard_Audit_Period_End_Date__c < LAST_N_DAYS:396 OR BR_Audit_Period_End_Date__c < LAST_N_DAYS:396 OR
                                Code_Signing_Audit_Period_End_Date__c < LAST_N_DAYS:396 OR EV_Code_Signing_Audit_Period_End_Date__c < LAST_N_DAYS:396 OR
                                EV_Audit_Period_End_Date__c < LAST_N_DAYS:396)
                            AND (Status__c IN  ('Included','Change Requested') OR Microsoft_Status__c IN ('Included','Change Requested')) 
                            AND CA_Owner_ID__c =: lstLoggedUser[0].AccountId
                            ORDER BY Name]; 
            
            //chekcing outdated intermediate certs.
            lstOutDatedIntermediateCerts = new List<Account>();
            lstOutDatedIntermediateCerts = [SELECT Name, CA_Owner__c, Standard_Audit_Period_End_Date__c,
                            BR_Audit_Period_End_Date__c, Code_Signing_Audit_Period_End_Date__c, 
                            EV_Code_Signing_Audit_Period_End_Date__c, EV_Audit_Period_End_Date__c                                                               
                            FROM Account 
                            WHERE Name != '<Fill in Cert Name>'
                            AND Record_Type_Name__c = 'Intermediate Certificate'
                            AND Revocation_Status__c NOT IN ('Revoked', 'Parent Cert Revoked')
                            AND Valid_To_GMT__c > TODAY   
                            AND (Standard_Audit_Period_End_Date__c < LAST_N_DAYS:396 OR BR_Audit_Period_End_Date__c < LAST_N_DAYS:396 OR
                                Code_Signing_Audit_Period_End_Date__c < LAST_N_DAYS:396 OR EV_Code_Signing_Audit_Period_End_Date__c < LAST_N_DAYS:396 OR
                                EV_Audit_Period_End_Date__c < LAST_N_DAYS:396)
                            AND Root_Status__c IN  ('Included','Change Requested') AND CA_Owner_ID__c =: lstLoggedUser[0].AccountId
                            ORDER BY Name]; 
            
            //checking if No audits are provided on intermediate certs
            lstIntermediateCertsNoAudits = new List<Account>();
            lstIntermediateCertsNoAudits = [SELECT Id, Name 
                            FROM Account 
                            WHERE Name != '<Fill in Cert Name>'
                            AND Record_Type_Name__c = 'Intermediate Certificate' 
                            AND Revocation_Status__c NOT IN ('Revoked', 'Parent Cert Revoked')
                            AND Valid_To_GMT__c > TODAY  
                            AND Technically_Constrained__c = false 
                            AND Audits_Same_as_Parent__c = false
                            AND Standard_Audit__c = null AND Code_Signing_Audit__c = null AND BR_Audit__c = null AND
                            EV_Audit__c = null AND EV_Code_Signing_Audit__c = null
                            AND CA_Owner_ID__c =: lstLoggedUser[0].AccountId
                            ORDER BY Name]; 
                            
            //checking if No CP/CPS are provided on intermediate certs
            lstIntermediateCertsNoCPCPS = new List<Account>();
            for(Account acc: [SELECT Id, Name,Certificate_Policy_CP__c,Certification_Practice_Statement_CPS__c  
                              FROM Account 
                              WHERE Name != '<Fill in Cert Name>'
                              AND Record_Type_Name__c = 'Intermediate Certificate' 
                              AND Revocation_Status__c NOT IN ('Revoked', 'Parent Cert Revoked')
                              AND Valid_To_GMT__c > TODAY   
                              AND Technically_Constrained__c = false
                              AND CP_CPS_Same_as_Parent__c = false
                              AND CA_Owner_ID__c =: lstLoggedUser[0].AccountId
                              ORDER BY Name]){
                if(string.isblank(acc.Certificate_Policy_CP__c) && string.isblank(acc.Certification_Practice_Statement_CPS__c)){
                    lstIntermediateCertsNoCPCPS.add(acc); 
                }
            }
            
            //checking for CA's Contact whoes dont logged more than 1.5 year.
            Date dtPast18Months = system.today().addMonths(-18); 
            
            //if it is CA user
            lstUsersNotUsed = new List<User>();
            if(lstLoggedUser[0].AccountId != null){
                lstUsersNotUsed = new List<User>([select Id, Name, Email, LastLoginDate, ContactId, Contact.Type__c 
                            FROM User 
                            Where IsActive = true 
                            AND (LastLoginDate = null or LastLoginDate <=: dtPast18Months)
                            AND AccountId =: lstLoggedUser[0].AccountId
                            ORDER BY Name]);
            }   
        }
    }
}